Fixed crash due to changed format of the Java 11 version string.
The problem was:

```
org.ant4eclipse.lib.core.exception.Ant4EclipseException: An invalid
format has been used: The given version '11.0.9.1' is invalid. Must
match: <major> [ '.' <minor> [ '.' <micro> [ '_' <qualifier> ] ] ]
```